### ISSUE TITLE
Uncaught Error: The workspace can only contain one instance of item [object Object]

### ISSUE THREAD

**Issue by johnapaz** [t--becker/tech-writer-ide#4]
1. Have one preview open
2. Open another preview on a different tab, in the original pane.

**Atom**: 1.15.0-beta3 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [Tech-Writer-IDE](https://github.com/t--becker/tech-writer-ide) package 0.1.1

### Stack Trace

Uncaught Error: The workspace can only contain one instance of item [object Object]

```
At /Applications/Atom Beta.app/Contents/Resources/app.asar/src/item-registry.js:11

Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (/app.asar/src/item-registry.js:11:15)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/app.asar/src/pane-container.js:389:25)
    at /app.asar/src/pane-container.js:374:28
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at Pane.module.exports.Pane.addItem (/app.asar/src/pane.js:506:20)
    at TechWriterIDEView.exports.default (/packages/Tech-Writer-IDE/lib/actions/preview.js:10:10)
    at TechWriterIDEView.assignFunction (/packages/Tech-Writer-IDE/lib/views/tech-writer-ide-view.js:40:12)
    at HTMLLIElement.btn.onclick (/packages/Tech-Writer-IDE/lib/views/tech-writer-ide-view.js:101:31)
```

### Commands

```
     -3:25.1.0 tree-view:duplicate (span.name.icon.icon-file-text)
  3x -2:39.9.0 core:backspace (input.hidden-input)
     -2:27.8.0 core:confirm (input.hidden-input)
     -2:13.4.0 tech-writer-ide:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-html-preview 0.1.22 
Tech-Writer-IDE 0.1.1 
```

**Comment by t--becker** [comment]
Updated the code to only allow one markdown previewer to be open at a time. This is a limitation in Atom, so I have to work around it. Update to the latest version of the plugin.
